"""changes date type

Revision ID: 1a21da0be53a
Revises: e3b038d3b0c2
Create Date: 2025-06-18 11:51:30.979652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a21da0be53a'
down_revision = 'e3b038d3b0c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('cpd_points',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('session_title',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('cpd_points',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('cpd_points',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('session_title',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('cpd_points',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
