"""initial migrations

Revision ID: 234d81c2ba42
Revises: 
Create Date: 2025-06-23 10:45:52.983101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234d81c2ba42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id_event', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=False),
    sa.Column('organizer', sa.String(length=100), nullable=False),
    sa.Column('cpd_points', sa.Integer(), nullable=False),
    sa.Column('session_title', sa.String(length=200), nullable=False),
    sa.Column('session_topic', sa.String(length=200), nullable=False),
    sa.Column('session_subtopic', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_event')
    )
    op.create_table('report',
    sa.Column('id_report', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id_event', sa.String(length=10), nullable=False),
    sa.Column('session_title', sa.String(length=50), nullable=False),
    sa.Column('cpd_points', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['id_event'], ['events.id_event'], ),
    sa.PrimaryKeyConstraint('id_report')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('events')
    # ### end Alembic commands ###
