"""empty message

Revision ID: 46e38557ee45
Revises: e6af7c7b1cf1
Create Date: 2025-06-19 21:20:23.841548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46e38557ee45'
down_revision = 'e6af7c7b1cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('cpd_points',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])
        batch_op.create_foreign_key(None, 'events', ['id_event'], ['id_event'])
        batch_op.drop_column('employeeid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employeeid', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('cpd_points',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    # ### end Alembic commands ###
