"""empty message

Revision ID: 6b0c3fcf9316
Revises: df909c393f59
Create Date: 2025-06-19 22:45:24.129126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0c3fcf9316'
down_revision = 'df909c393f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint('report_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['employeeid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('report_ibfk_2', 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###
