"""add must chagne password

Revision ID: 801c894e6fef
Revises: f9143fe14967
Create Date: 2025-07-14 16:42:49.699271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801c894e6fef'
down_revision = 'f9143fe14967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
