"""empty message

Revision ID: b53bacade9ec
Revises: 034c8e73bb2d
Create Date: 2025-06-19 21:23:51.015373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53bacade9ec'
down_revision = '034c8e73bb2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'events', ['id_event'], ['id_event'])
        batch_op.create_foreign_key(None, 'employee', ['employeeid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
