"""add gender in employee

Revision ID: d05a435e894b
Revises: c46b00eb584a
Create Date: 2025-07-23 16:18:29.303211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05a435e894b'
down_revision = 'c46b00eb584a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('gender')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
