"""empty message

Revision ID: df909c393f59
Revises: d908c3b7a887
Create Date: 2025-06-19 22:00:13.433065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df909c393f59'
down_revision = 'd908c3b7a887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('employeeid',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('report_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])
        batch_op.drop_column('employeeid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employeeid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('report_ibfk_2', 'employee', ['employeeid'], ['id'])
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('employeeid',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    # ### end Alembic commands ###
