"""initial migration

Revision ID: e3b038d3b0c2
Revises: 
Create Date: 2025-06-10 23:47:20.929639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b038d3b0c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employeeid', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id_event', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=100), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=False),
    sa.Column('organizer', sa.String(length=100), nullable=False),
    sa.Column('cpd_points', sa.String(length=50), nullable=False),
    sa.Column('session_title', sa.String(length=200), nullable=False),
    sa.Column('session_topic', sa.String(length=200), nullable=False),
    sa.Column('session_subtopic', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_event')
    )
    op.create_table('report',
    sa.Column('id_report', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('employeeid', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('id_event', sa.String(length=50), nullable=False),
    sa.Column('session_title', sa.String(length=200), nullable=False),
    sa.Column('cpd_points', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_report')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('report')
    op.drop_table('events')
    op.drop_table('employee')
    # ### end Alembic commands ###
